# Generated by Django 5.0.6 on 2024-05-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("database_name", models.CharField(max_length=100, unique=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
